// Bridge — wraps Wails Go bindings.
// In dev mode (wails dev), these call into the real Go backend.
// The wailsjs/go/main/App bindings are auto-generated by Wails.

import { GetConfig, GetConfigPath, GetGlobalFolder, GetAllStatus, RefreshStatus, CloneRepo, PullRepo, Discover, AddDiscoveredRepos, CredentialVerify, CredentialDelete, ReloadConfig, DeleteRepo, AddAccount, UpdateAccount, RenameAccount, CredentialSetupGCM, CredentialStoreToken, CredentialSetupSSH, GetTokenGuide, DeleteAccount, ChangeCredentialType, OpenFileInEditor, IsFirstRun, PickFolder, SetGlobalFolder, GetAppVersion, FetchRepo, FetchAllRepos, GetRepoDetail, GetPeriodicSync, SetPeriodicSync } from '../../wailsjs/go/main/App';
import { EventsOn } from '../../wailsjs/runtime/runtime';

import type { ConfigDTO, StatusResult, CredentialStatus } from './types';

export const bridge = {
  getConfig: (): Promise<ConfigDTO> => GetConfig(),
  reloadConfig: (): Promise<ConfigDTO> => ReloadConfig(),
  getConfigPath: (): Promise<string> => GetConfigPath(),
  getGlobalFolder: (): Promise<string> => GetGlobalFolder(),
  getAllStatus: (): Promise<StatusResult[]> => GetAllStatus(),
  refreshStatus: (): Promise<void> => RefreshStatus(),
  cloneRepo: (sourceKey: string, repoKey: string): Promise<void> => CloneRepo(sourceKey, repoKey),
  pullRepo: (sourceKey: string, repoKey: string): Promise<void> => PullRepo(sourceKey, repoKey),
  discover: (accountKey: string): Promise<void> => Discover(accountKey),
  addDiscoveredRepos: (sourceKey: string, repos: string[]): Promise<void> => AddDiscoveredRepos(sourceKey, repos),
  credentialVerify: (accountKey: string): Promise<CredentialStatus> => CredentialVerify(accountKey),
  credentialDelete: (accountKey: string): Promise<any> => CredentialDelete(accountKey),
  renameAccount: (oldKey: string, newKey: string): Promise<void> => RenameAccount(oldKey, newKey),
  deleteRepo: (sourceKey: string, repoKey: string): Promise<void> => DeleteRepo(sourceKey, repoKey),
  addAccount: (req: any): Promise<void> => AddAccount(req),
  updateAccount: (req: any): Promise<void> => UpdateAccount(req),
  credentialSetupGCM: (accountKey: string): Promise<any> => CredentialSetupGCM(accountKey),
  credentialStoreToken: (accountKey: string, token: string): Promise<any> => CredentialStoreToken(accountKey, token),
  credentialSetupSSH: (accountKey: string): Promise<any> => CredentialSetupSSH(accountKey),
  getTokenGuide: (accountKey: string): Promise<any> => GetTokenGuide(accountKey),
  deleteAccount: (accountKey: string): Promise<void> => DeleteAccount(accountKey),
  changeCredentialType: (accountKey: string, newType: string): Promise<void> => ChangeCredentialType(accountKey, newType),
  openFileInEditor: (path: string): Promise<void> => OpenFileInEditor(path),
  isFirstRun: (): Promise<boolean> => IsFirstRun(),
  pickFolder: (title: string): Promise<string> => PickFolder(title),
  setGlobalFolder: (folder: string): Promise<void> => SetGlobalFolder(folder),
  getAppVersion: (): Promise<string> => GetAppVersion(),
  fetchRepo: (sourceKey: string, repoKey: string): Promise<void> => FetchRepo(sourceKey, repoKey),
  fetchAllRepos: (): Promise<void> => FetchAllRepos(),
  getRepoDetail: (sourceKey: string, repoKey: string): Promise<any> => GetRepoDetail(sourceKey, repoKey),
  getPeriodicSync: (): Promise<string> => GetPeriodicSync(),
  setPeriodicSync: (interval: string): Promise<void> => SetPeriodicSync(interval),
};

export const events = {
  on: EventsOn,
};
