// Bridge — wraps Wails Go bindings.
// In dev mode (wails dev), these call into the real Go backend.
// The wailsjs/go/main/App bindings are auto-generated by Wails.

import { GetConfig, GetConfigPath, GetGlobalFolder, GetAllStatus, RefreshStatus, CloneRepo, PullRepo, Discover, AddDiscoveredRepos, CredentialVerify, CredentialDelete, ReloadConfig, DeleteRepo, AddAccount, UpdateAccount, RenameAccount, CredentialSetupGCM, CredentialStoreToken, CredentialSetupSSH, CredentialRegenerateSSH, GetTokenGuide, AccountDeletionImpact, DeleteAccount, ChangeCredentialType, OpenAccountFolder, OpenAccountInApp, OpenAccountInBrowser, OpenAccountInTerminal, OpenAccountInAIHarness, OpenFileInEditor, OpenInExplorer, OpenInApp, OpenInTerminal, OpenInAIHarness, OpenInBrowser, DetectEditors, DetectTerminals, DetectAIHarnesses, IsFirstRun, GetConfigLoadError, AcknowledgeConfigError, RepairConfig, ListConfigBackups, RestoreFromBackup, PickFolder, SetGlobalFolder, GetAppVersion, GetOS, FetchRepo, FetchAllRepos, GetRepoDetail, GetLanguage, SetLanguage, GetPeriodicSync, SetPeriodicSync, GetViewMode, SetViewMode, ShowWindow, CheckGlobalIdentity, RemoveGlobalIdentity, IsGlobalGCMConfigNeeded, CheckGlobalGCMConfig, FixGlobalGCMConfig, CheckGlobalGitignore, InstallGlobalGitignore, RecommendedGlobalGitignoreBody, GetCheckGlobalGitignore, SetCheckGlobalGitignore, GetAutostart, SetAutostart, GetMirrorStatus, SetupMirrorRepo, AddMirrorGroup, DeleteMirrorGroup, AddMirrorRepo, DeleteMirrorRepo, CheckMirrorCredentials, ListRemoteRepos, DiscoverMirrors, ApplyDiscoveredMirrors, ListAccountOrgs, CreateNewRepo, IsPositionOnScreen, ApplyUpdate, PreviewSweep, ConfirmSweep, FindOrphans, AdoptOrphans, ShowErrorDialog, GetPRSettings, SetPRBadgesEnabled, SetPRIncludeDrafts, GetPRsForRepo, RefreshAllPRs, ListWorkspaces, GetWorkspace, CreateWorkspace, UpdateWorkspace, DeleteWorkspace, AddWorkspaceMember, RemoveWorkspaceMember, GenerateWorkspace, OpenWorkspace, DiscoverWorkspaces, DoctorRun, DoctorPrecheck, ListMoveDestinationOwners, PreflightMove, MoveRepo, CheckMoveReadiness } from '../../wailsjs/go/main/App';
import { EventsOn } from '../../wailsjs/runtime/runtime';

import type { ConfigDTO, StatusResult, CredentialStatus, EditorInfo, TerminalInfo, AIHarnessInfo, OrphanRepoDTO, AdoptResultDTO, AccountDeletionImpactDTO, ConfigRepairResult, ConfigBackupInfo, PRSettingsDTO, PRSummaryDTO, WorkspaceDTO, WorkspaceMemberDTO, WorkspaceCreateRequest, WorkspaceUpdateRequest, WorkspaceGenerateResult, WorkspaceListResult, DiscoverWorkspacesResult, MoveOwnerOption, MoveRequestDTO, MovePreflightDTO, MoveReadinessDTO } from './types';

export const bridge = {
  getConfig: (): Promise<ConfigDTO> => GetConfig() as unknown as Promise<ConfigDTO>,
  reloadConfig: (): Promise<ConfigDTO> => ReloadConfig() as unknown as Promise<ConfigDTO>,
  getConfigPath: (): Promise<string> => GetConfigPath(),
  getGlobalFolder: (): Promise<string> => GetGlobalFolder(),
  getAllStatus: (): Promise<StatusResult[]> => GetAllStatus(),
  refreshStatus: (): Promise<void> => RefreshStatus(),
  cloneRepo: (sourceKey: string, repoKey: string): Promise<void> => CloneRepo(sourceKey, repoKey),
  pullRepo: (sourceKey: string, repoKey: string): Promise<void> => PullRepo(sourceKey, repoKey),
  discover: (accountKey: string): Promise<void> => Discover(accountKey),
  addDiscoveredRepos: (sourceKey: string, repos: string[]): Promise<void> => AddDiscoveredRepos(sourceKey, repos),
  credentialVerify: (accountKey: string): Promise<CredentialStatus> => CredentialVerify(accountKey),
  credentialDelete: (accountKey: string): Promise<any> => CredentialDelete(accountKey),
  renameAccount: (oldKey: string, newKey: string): Promise<void> => RenameAccount(oldKey, newKey),
  deleteRepo: (sourceKey: string, repoKey: string): Promise<void> => DeleteRepo(sourceKey, repoKey),
  addAccount: (req: any): Promise<void> => AddAccount(req),
  updateAccount: (req: any): Promise<void> => UpdateAccount(req),
  credentialSetupGCM: (accountKey: string): Promise<any> => CredentialSetupGCM(accountKey),
  credentialStoreToken: (accountKey: string, token: string): Promise<any> => CredentialStoreToken(accountKey, token),
  credentialSetupSSH: (accountKey: string): Promise<any> => CredentialSetupSSH(accountKey),
  credentialRegenerateSSH: (accountKey: string): Promise<any> => CredentialRegenerateSSH(accountKey),
  getTokenGuide: (accountKey: string): Promise<any> => GetTokenGuide(accountKey),
  accountDeletionImpact: (accountKey: string): Promise<AccountDeletionImpactDTO> => AccountDeletionImpact(accountKey) as Promise<AccountDeletionImpactDTO>,
  deleteAccount: (accountKey: string): Promise<void> => DeleteAccount(accountKey),
  changeCredentialType: (accountKey: string, newType: string): Promise<void> => ChangeCredentialType(accountKey, newType),
  openFileInEditor: (path: string): Promise<void> => OpenFileInEditor(path),
  openInExplorer: (path: string): Promise<void> => OpenInExplorer(path),
  openInApp: (path: string, command: string): Promise<void> => OpenInApp(path, command),
  openInTerminal: (path: string, command: string, args: string[]): Promise<void> => OpenInTerminal(path, command, args),
  openInAIHarness: (path: string, command: string, args: string[]): Promise<void> => OpenInAIHarness(path, command, args),
  openInBrowser: (url: string): Promise<void> => OpenInBrowser(url),
  openAccountFolder: (accountKey: string): Promise<void> => OpenAccountFolder(accountKey),
  openAccountInApp: (accountKey: string, command: string): Promise<void> => OpenAccountInApp(accountKey, command),
  openAccountInTerminal: (accountKey: string, command: string, args: string[]): Promise<void> => OpenAccountInTerminal(accountKey, command, args),
  openAccountInAIHarness: (accountKey: string, command: string, args: string[]): Promise<void> => OpenAccountInAIHarness(accountKey, command, args),
  openAccountInBrowser: (accountKey: string): Promise<void> => OpenAccountInBrowser(accountKey),
  detectEditors: (): Promise<EditorInfo[]> => DetectEditors(),
  detectTerminals: (): Promise<TerminalInfo[]> => DetectTerminals(),
  detectAIHarnesses: (): Promise<AIHarnessInfo[]> => DetectAIHarnesses(),
  isFirstRun: (): Promise<boolean> => IsFirstRun(),
  getConfigLoadError: (): Promise<string> => GetConfigLoadError(),
  acknowledgeConfigError: (): Promise<void> => AcknowledgeConfigError(),
  repairConfig: (): Promise<ConfigRepairResult> => RepairConfig() as Promise<ConfigRepairResult>,
  listConfigBackups: (): Promise<ConfigBackupInfo[]> => ListConfigBackups() as Promise<ConfigBackupInfo[]>,
  restoreFromBackup: (path: string): Promise<ConfigRepairResult> => RestoreFromBackup(path) as Promise<ConfigRepairResult>,
  pickFolder: (title: string): Promise<string> => PickFolder(title),
  setGlobalFolder: (folder: string): Promise<void> => SetGlobalFolder(folder),
  getAppVersion: (): Promise<string> => GetAppVersion(),
  getOS: (): Promise<string> => GetOS(),
  fetchRepo: (sourceKey: string, repoKey: string): Promise<void> => FetchRepo(sourceKey, repoKey),
  fetchAllRepos: (): Promise<void> => FetchAllRepos(),
  getRepoDetail: (sourceKey: string, repoKey: string): Promise<any> => GetRepoDetail(sourceKey, repoKey),
  getLanguage: (): Promise<string> => GetLanguage(),
  setLanguage: (lang: string): Promise<void> => SetLanguage(lang),
  getPeriodicSync: (): Promise<string> => GetPeriodicSync(),
  setPeriodicSync: (interval: string): Promise<void> => SetPeriodicSync(interval),
  getViewMode: (): Promise<string> => GetViewMode(),
  setViewMode: (mode: string): Promise<any> => SetViewMode(mode),
  isPositionOnScreen: (x: number, y: number, w: number, h: number): Promise<boolean> => IsPositionOnScreen(x, y, w, h),
  showWindow: (): Promise<void> => ShowWindow(),
  checkGlobalIdentity: (): Promise<any> => CheckGlobalIdentity(),
  removeGlobalIdentity: (): Promise<void> => RemoveGlobalIdentity(),
  isGlobalGCMConfigNeeded: (): Promise<boolean> => IsGlobalGCMConfigNeeded(),
  checkGlobalGCMConfig: (): Promise<any> => CheckGlobalGCMConfig(),
  fixGlobalGCMConfig: (): Promise<void> => FixGlobalGCMConfig(),
  checkGlobalGitignore: (): Promise<any> => CheckGlobalGitignore(),
  installGlobalGitignore: (): Promise<any> => InstallGlobalGitignore(),
  recommendedGlobalGitignoreBody: (): Promise<string> => RecommendedGlobalGitignoreBody(),
  getCheckGlobalGitignore: (): Promise<boolean> => GetCheckGlobalGitignore(),
  setCheckGlobalGitignore: (enabled: boolean): Promise<void> => SetCheckGlobalGitignore(enabled),
  getAutostart: (): Promise<boolean> => GetAutostart(),
  setAutostart: (enable: boolean): Promise<void> => SetAutostart(enable),
  getMirrorStatus: (mirrorKey: string): Promise<void> => GetMirrorStatus(mirrorKey),
  setupMirrorRepo: (mirrorKey: string, repoKey: string): Promise<void> => SetupMirrorRepo(mirrorKey, repoKey),
  addMirrorGroup: (key: string, accountSrc: string, accountDst: string): Promise<void> => AddMirrorGroup(key, accountSrc, accountDst),
  deleteMirrorGroup: (key: string): Promise<void> => DeleteMirrorGroup(key),
  addMirrorRepo: (mirrorKey: string, repoKey: string, direction: string, origin: string): Promise<void> => AddMirrorRepo(mirrorKey, repoKey, direction, origin),
  deleteMirrorRepo: (mirrorKey: string, repoKey: string): Promise<void> => DeleteMirrorRepo(mirrorKey, repoKey),
  checkMirrorCredentials: (accountKey: string): Promise<any> => CheckMirrorCredentials(accountKey),
  listRemoteRepos: (accountKey: string): Promise<any[]> => ListRemoteRepos(accountKey),
  discoverMirrors: (): Promise<void> => DiscoverMirrors(),
  applyDiscoveredMirrors: (): Promise<void> => ApplyDiscoveredMirrors(),
  listAccountOrgs: (accountKey: string): Promise<string[]> => ListAccountOrgs(accountKey),
  createNewRepo: (accountKey: string, owner: string, repoName: string, description: string, isPrivate: boolean, cloneAfter: boolean): Promise<void> => CreateNewRepo(accountKey, owner, repoName, description, isPrivate, cloneAfter),
  applyUpdate: (): Promise<void> => ApplyUpdate(),
  previewSweep: (sourceKey: string, repoKey: string): Promise<any> => PreviewSweep(sourceKey, repoKey),
  confirmSweep: (sourceKey: string, repoKey: string): Promise<any> => ConfirmSweep(sourceKey, repoKey),
  findOrphans: (): Promise<OrphanRepoDTO[]> => FindOrphans(),
  adoptOrphans: (repoKeys: string[]): Promise<AdoptResultDTO> => AdoptOrphans(repoKeys),
  showErrorDialog: (title: string, message: string): Promise<void> => ShowErrorDialog(title, message),
  getPRSettings: (): Promise<PRSettingsDTO> => GetPRSettings() as Promise<PRSettingsDTO>,
  setPRBadgesEnabled: (enabled: boolean): Promise<void> => SetPRBadgesEnabled(enabled),
  setPRIncludeDrafts: (enabled: boolean): Promise<void> => SetPRIncludeDrafts(enabled),
  getPRsForRepo: (sourceKey: string, repoKey: string): Promise<PRSummaryDTO> => GetPRsForRepo(sourceKey, repoKey) as Promise<PRSummaryDTO>,
  refreshAllPRs: (): Promise<void> => RefreshAllPRs(),
  listWorkspaces: (): Promise<WorkspaceListResult> => ListWorkspaces() as Promise<WorkspaceListResult>,
  getWorkspace: (key: string): Promise<WorkspaceDTO> => GetWorkspace(key) as Promise<WorkspaceDTO>,
  createWorkspace: (req: WorkspaceCreateRequest): Promise<void> => CreateWorkspace(req as any),
  updateWorkspace: (key: string, req: WorkspaceUpdateRequest): Promise<void> => UpdateWorkspace(key, req as any),
  deleteWorkspace: (key: string): Promise<void> => DeleteWorkspace(key),
  addWorkspaceMember: (key: string, member: WorkspaceMemberDTO): Promise<void> => AddWorkspaceMember(key, member as any),
  removeWorkspaceMember: (key: string, source: string, repo: string): Promise<void> => RemoveWorkspaceMember(key, source, repo),
  generateWorkspace: (key: string): Promise<WorkspaceGenerateResult> => GenerateWorkspace(key) as Promise<WorkspaceGenerateResult>,
  openWorkspace: (key: string): Promise<void> => OpenWorkspace(key),
  discoverWorkspaces: (): Promise<DiscoverWorkspacesResult> => DiscoverWorkspaces() as Promise<DiscoverWorkspacesResult>,
  doctorRun: (): Promise<DoctorReport> => DoctorRun() as Promise<DoctorReport>,
  doctorPrecheck: (credentialType: string): Promise<DoctorPrecheckDTO> => DoctorPrecheck(credentialType) as Promise<DoctorPrecheckDTO>,
  listMoveDestinationOwners: (sourceKey: string): Promise<MoveOwnerOption[]> => ListMoveDestinationOwners(sourceKey) as Promise<MoveOwnerOption[]>,
  preflightMove: (req: MoveRequestDTO): Promise<MovePreflightDTO> => PreflightMove(req as any) as Promise<MovePreflightDTO>,
  moveRepo: (req: MoveRequestDTO): Promise<void> => MoveRepo(req as any),
  checkMoveReadiness: (sourceSourceKey: string, destAccountKey: string, deleteSource: boolean): Promise<MoveReadinessDTO> => CheckMoveReadiness(sourceSourceKey, destAccountKey, deleteSource) as Promise<MoveReadinessDTO>,
};

// ── Doctor types (mirror cmd/gui/app.go) ──
export interface DoctorToolDTO {
  name: string;
  displayName: string;
  purpose: string;
  found: boolean;
  path?: string;
  version?: string;
  required: boolean;
  requiredFor?: string;
  installHint?: string;
}

export interface DoctorReport {
  tools: DoctorToolDTO[];
  allOk: boolean;
  missingReq: number;
  missingOpt: number;
}

export interface DoctorPrecheckDTO {
  ok: boolean;
  summary?: string;
  hint?: string;
  missing?: DoctorToolDTO[];
}

export const events = {
  on: EventsOn,
};
