package workspace

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/LuisPalacios/gitbox/pkg/config"
	"github.com/LuisPalacios/gitbox/pkg/git"
)

// tmuxinatorSupported reports whether the current host can launch tmuxinator.
// macOS and Linux run it natively. Windows runs it via WSL when the wsl.exe
// probe succeeds; this lets Windows users get real tmuxinator support instead
// of the previous platform-unsupported stub.
func tmuxinatorSupported() bool {
	switch runtime.GOOS {
	case "darwin", "linux":
		return true
	case "windows":
		return git.IsWSLAvailable()
	default:
		return false
	}
}

// ErrTmuxinatorUnsupported is returned when a tmuxinator workspace is
// generated or opened on a platform that cannot launch tmuxinator (Windows
// without WSL, or any other unsupported OS).
var ErrTmuxinatorUnsupported = fmt.Errorf("tmuxinator workspaces are not supported on this host (Windows requires WSL)")

// defaultTmuxinatorFile returns the absolute on-disk path where the
// generated YAML for a workspace key should land. On Windows this is the
// Windows-accessible UNC path of the WSL-side ~/.tmuxinator/<key>.yml so
// Generate can write through the Windows filesystem view of WSL.
func defaultTmuxinatorFile(key string) (string, error) {
	if !tmuxinatorSupported() {
		return "", ErrTmuxinatorUnsupported
	}
	if runtime.GOOS == "windows" {
		home, err := git.WSLHome()
		if err != nil {
			return "", fmt.Errorf("resolving WSL home: %w", err)
		}
		linuxPath := path.Join(home, ".tmuxinator", key+".yml")
		winPath, err := git.WSLPath(linuxPath)
		if err != nil {
			return "", fmt.Errorf("translating %q to a Windows path: %w", linuxPath, err)
		}
		return winPath, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".tmuxinator", key+".yml"), nil
}

func generateTmuxinator(key string, w config.Workspace, memberPaths []string) (GenerateResult, error) {
	file := w.File
	if file == "" {
		f, err := defaultTmuxinatorFile(key)
		if err != nil {
			return GenerateResult{}, err
		}
		file = f
	} else if !tmuxinatorSupported() {
		return GenerateResult{}, ErrTmuxinatorUnsupported
	}

	layout := w.Layout
	if layout == "" {
		layout = config.WorkspaceLayoutWindows
	}

	name := w.EffectiveName(key)

	// On Windows, tmuxinator runs inside WSL — translate every member's
	// Windows path into its Linux-side equivalent so `root:` and `cd` work
	// inside the WSL shell.
	yamlPaths := memberPaths
	if runtime.GOOS == "windows" {
		converted := make([]string, len(memberPaths))
		for i, p := range memberPaths {
			lp, err := git.WSLLinuxPath(p)
			if err != nil {
				return GenerateResult{}, fmt.Errorf("workspace %q: translating %q to WSL: %w", key, p, err)
			}
			converted[i] = lp
		}
		yamlPaths = converted
	}

	var body string
	switch layout {
	case config.WorkspaceLayoutWindows:
		body = renderWindowsPerRepo(name, w.Members, yamlPaths)
	case config.WorkspaceLayoutSplit:
		body = renderSplitPanes(name, w.Members, yamlPaths)
	default:
		return GenerateResult{}, fmt.Errorf("workspace %q: unknown tmuxinator layout %q", key, layout)
	}

	return GenerateResult{
		File:          file,
		Content:       []byte(body),
		ResolvedPaths: memberPaths,
	}, nil
}

func renderWindowsPerRepo(name string, members []config.WorkspaceMember, paths []string) string {
	var b strings.Builder
	b.WriteString("# Generated by gitbox. Edit only the body; the name field must stay in sync\n")
	b.WriteString("# with the config workspace key.\n")
	fmt.Fprintf(&b, "name: %s\n", yamlString(name))
	b.WriteString("root: ~/\n")
	b.WriteString("\n")
	b.WriteString("windows:\n")
	for i, m := range members {
		label := labelForMember(m)
		fmt.Fprintf(&b, "  - %s:\n", yamlString(label))
		fmt.Fprintf(&b, "      root: %s\n", yamlString(paths[i]))
		b.WriteString("      panes:\n")
		b.WriteString("        - null\n")
	}
	return b.String()
}

func renderSplitPanes(name string, members []config.WorkspaceMember, paths []string) string {
	var b strings.Builder
	b.WriteString("# Generated by gitbox.\n")
	fmt.Fprintf(&b, "name: %s\n", yamlString(name))
	b.WriteString("root: ~/\n")
	b.WriteString("\n")
	b.WriteString("windows:\n")
	b.WriteString("  - all:\n")
	b.WriteString("      layout: tiled\n")
	b.WriteString("      panes:\n")
	for i, m := range members {
		_ = m
		fmt.Fprintf(&b, "        - cd %s\n", yamlString(paths[i]))
	}
	return b.String()
}

// yamlString quotes a scalar when it would otherwise break YAML parsing, and
// emits it plain when it's safe. Keeps generated files readable and diffable.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Quote when the value contains any YAML-special character or whitespace
	// oddities, or starts with a character YAML treats specially.
	if strings.ContainsAny(s, `:#"'\`+"\t\n\r`*&!|>%@") {
		escaped := strings.ReplaceAll(s, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	// Bare strings that look like booleans, nulls, or numbers must be quoted.
	lower := strings.ToLower(s)
	switch lower {
	case "true", "false", "yes", "no", "null", "~", "on", "off":
		return `"` + s + `"`
	}
	if looksNumeric(s) {
		return `"` + s + `"`
	}
	// Leading dash, question mark, or bracket characters are YAML indicators.
	switch s[0] {
	case '-', '?', '[', ']', '{', '}', ',':
		return `"` + s + `"`
	}
	return s
}

func looksNumeric(s string) bool {
	hasDigit := false
	for i, r := range s {
		switch {
		case r >= '0' && r <= '9':
			hasDigit = true
		case (r == '-' || r == '+') && i == 0:
		case r == '.' || r == 'e' || r == 'E':
		default:
			return false
		}
	}
	return hasDigit
}
