// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {credential} from '../models';
import {identity} from '../models';

export function AccountDeletionImpact(arg1:string):Promise<main.AccountDeletionImpactDTO>;

export function AcknowledgeConfigError():Promise<void>;

export function AddAccount(arg1:main.AddAccountRequest):Promise<void>;

export function AddDiscoveredRepos(arg1:string,arg2:Array<string>):Promise<void>;

export function AddMirrorGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddMirrorRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddWorkspaceMember(arg1:string,arg2:main.WorkspaceMemberDTO):Promise<void>;

export function AdoptOrphans(arg1:Array<string>):Promise<main.AdoptResultDTO>;

export function ApplyDiscoveredMirrors():Promise<void>;

export function ApplyUpdate():Promise<void>;

export function ChangeCredentialType(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<void>;

export function CheckGlobalGCMConfig():Promise<credential.GlobalGCMConfigStatus>;

export function CheckGlobalIdentity():Promise<identity.GlobalIdentityStatus>;

export function CheckMirrorCredentials(arg1:string):Promise<main.MirrorCredentialCheck>;

export function CloneRepo(arg1:string,arg2:string):Promise<void>;

export function ConfirmSweep(arg1:string,arg2:string):Promise<main.SweepDeleteDTO>;

export function CreateNewRepo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function CreateWorkspace(arg1:main.WorkspaceCreateRequest):Promise<void>;

export function CredentialDelete(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialRegenerateSSH(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupGCM(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupSSH(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialStoreToken(arg1:string,arg2:string):Promise<main.CredentialSetupResult>;

export function CredentialVerify(arg1:string):Promise<main.CredentialStatus>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteMirrorGroup(arg1:string):Promise<void>;

export function DeleteMirrorRepo(arg1:string,arg2:string):Promise<void>;

export function DeleteRepo(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DetectAIHarnesses():Promise<Array<main.AIHarnessInfo>>;

export function DetectEditors():Promise<Array<main.EditorInfo>>;

export function DetectTerminals():Promise<Array<main.TerminalInfo>>;

export function Discover(arg1:string):Promise<void>;

export function DiscoverMirrors():Promise<void>;

export function DiscoverWorkspaces():Promise<main.DiscoverWorkspacesResult>;

export function DoctorPrecheck(arg1:string):Promise<main.DoctorPrecheckDTO>;

export function DoctorRun():Promise<main.DoctorReport>;

export function FetchAllRepos():Promise<void>;

export function FetchRepo(arg1:string,arg2:string):Promise<void>;

export function FindOrphans():Promise<Array<main.OrphanRepoDTO>>;

export function FixGlobalGCMConfig():Promise<void>;

export function GenerateWorkspace(arg1:string):Promise<main.WorkspaceGenerateResult>;

export function GetAllStatus():Promise<Array<main.StatusResult>>;

export function GetAppVersion():Promise<string>;

export function GetAutostart():Promise<boolean>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetConfigLoadError():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetGlobalFolder():Promise<string>;

export function GetMirrorStatus(arg1:string):Promise<void>;

export function GetOS():Promise<string>;

export function GetPRSettings():Promise<main.PRSettingsDTO>;

export function GetPRsForRepo(arg1:string,arg2:string):Promise<main.PRSummaryDTO>;

export function GetPeriodicSync():Promise<string>;

export function GetRepoDetail(arg1:string,arg2:string):Promise<main.RepoDetail>;

export function GetTokenGuide(arg1:string):Promise<main.TokenGuideInfo>;

export function GetViewMode():Promise<string>;

export function GetWorkspace(arg1:string):Promise<main.WorkspaceDTO>;

export function IsFirstRun():Promise<boolean>;

export function IsGlobalGCMConfigNeeded():Promise<boolean>;

export function IsPositionOnScreen(arg1:number,arg2:number,arg3:number,arg4:number):Promise<boolean>;

export function IsTestMode():Promise<boolean>;

export function ListAccountOrgs(arg1:string):Promise<Array<string>>;

export function ListConfigBackups():Promise<Array<main.ConfigBackupInfo>>;

export function ListRemoteRepos(arg1:string):Promise<Array<main.DiscoverResult>>;

export function ListWorkspaces():Promise<main.WorkspaceListResult>;

export function OpenAccountFolder(arg1:string):Promise<void>;

export function OpenAccountInAIHarness(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function OpenAccountInApp(arg1:string,arg2:string):Promise<void>;

export function OpenAccountInBrowser(arg1:string):Promise<void>;

export function OpenAccountInTerminal(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenInAIHarness(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function OpenInApp(arg1:string,arg2:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function PreviewSweep(arg1:string,arg2:string):Promise<main.SweepPreviewDTO>;

export function PullRepo(arg1:string,arg2:string):Promise<void>;

export function RefreshAllPRs():Promise<void>;

export function RefreshStatus():Promise<void>;

export function ReloadConfig():Promise<main.ConfigDTO>;

export function RemoveGlobalIdentity():Promise<void>;

export function RemoveWorkspaceMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameAccount(arg1:string,arg2:string):Promise<void>;

export function RepairConfig():Promise<main.ConfigRepairResult>;

export function RestoreFromBackup(arg1:string):Promise<main.ConfigRepairResult>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetGlobalFolder(arg1:string):Promise<void>;

export function SetPRBadgesEnabled(arg1:boolean):Promise<void>;

export function SetPRIncludeDrafts(arg1:boolean):Promise<void>;

export function SetPeriodicSync(arg1:string):Promise<void>;

export function SetViewMode(arg1:string):Promise<main.WindowStateDTO>;

export function SetupMirrorRepo(arg1:string,arg2:string):Promise<void>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function SyncAIHarnesses():Promise<void>;

export function SyncEditors():Promise<void>;

export function SyncTerminals():Promise<void>;

export function UpdateAccount(arg1:main.UpdateAccountRequest):Promise<void>;

export function UpdateWorkspace(arg1:string,arg2:main.WorkspaceUpdateRequest):Promise<void>;
