// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddDiscoveredRepos(arg1, arg2) {
  return window['go']['main']['App']['AddDiscoveredRepos'](arg1, arg2);
}

export function ChangeCredentialType(arg1, arg2) {
  return window['go']['main']['App']['ChangeCredentialType'](arg1, arg2);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function CredentialDelete(arg1) {
  return window['go']['main']['App']['CredentialDelete'](arg1);
}

export function CredentialSetupGCM(arg1) {
  return window['go']['main']['App']['CredentialSetupGCM'](arg1);
}

export function CredentialSetupSSH(arg1) {
  return window['go']['main']['App']['CredentialSetupSSH'](arg1);
}

export function CredentialStoreToken(arg1, arg2) {
  return window['go']['main']['App']['CredentialStoreToken'](arg1, arg2);
}

export function CredentialVerify(arg1) {
  return window['go']['main']['App']['CredentialVerify'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteRepo(arg1, arg2) {
  return window['go']['main']['App']['DeleteRepo'](arg1, arg2);
}

export function Discover(arg1) {
  return window['go']['main']['App']['Discover'](arg1);
}

export function FetchAllRepos() {
  return window['go']['main']['App']['FetchAllRepos']();
}

export function FetchRepo(arg1, arg2) {
  return window['go']['main']['App']['FetchRepo'](arg1, arg2);
}

export function GetAllStatus() {
  return window['go']['main']['App']['GetAllStatus']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetGlobalFolder() {
  return window['go']['main']['App']['GetGlobalFolder']();
}

export function GetPeriodicSync() {
  return window['go']['main']['App']['GetPeriodicSync']();
}

export function GetRepoDetail(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDetail'](arg1, arg2);
}

export function GetTokenGuide(arg1) {
  return window['go']['main']['App']['GetTokenGuide'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PullRepo(arg1, arg2) {
  return window['go']['main']['App']['PullRepo'](arg1, arg2);
}

export function RefreshStatus() {
  return window['go']['main']['App']['RefreshStatus']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function SetGlobalFolder(arg1) {
  return window['go']['main']['App']['SetGlobalFolder'](arg1);
}

export function SetPeriodicSync(arg1) {
  return window['go']['main']['App']['SetPeriodicSync'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
