// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:main.AddAccountRequest):Promise<void>;

export function AddDiscoveredRepos(arg1:string,arg2:Array<string>):Promise<void>;

export function ChangeCredentialType(arg1:string,arg2:string):Promise<void>;

export function CloneRepo(arg1:string,arg2:string):Promise<void>;

export function CredentialDelete(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupGCM(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupSSH(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialStoreToken(arg1:string,arg2:string):Promise<main.CredentialSetupResult>;

export function CredentialVerify(arg1:string):Promise<main.CredentialStatus>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteRepo(arg1:string,arg2:string):Promise<void>;

export function Discover(arg1:string):Promise<void>;

export function FetchAllRepos():Promise<void>;

export function FetchRepo(arg1:string,arg2:string):Promise<void>;

export function GetAllStatus():Promise<Array<main.StatusResult>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetConfigPath():Promise<string>;

export function GetGlobalFolder():Promise<string>;

export function GetPeriodicSync():Promise<string>;

export function GetRepoDetail(arg1:string,arg2:string):Promise<main.RepoDetail>;

export function GetTokenGuide(arg1:string):Promise<main.TokenGuideInfo>;

export function IsFirstRun():Promise<boolean>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function PullRepo(arg1:string,arg2:string):Promise<void>;

export function RefreshStatus():Promise<void>;

export function ReloadConfig():Promise<main.ConfigDTO>;

export function SetGlobalFolder(arg1:string):Promise<void>;

export function SetPeriodicSync(arg1:string):Promise<void>;

export function UpdateAccount(arg1:main.UpdateAccountRequest):Promise<void>;
