// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddDiscoveredRepos(arg1, arg2) {
  return window['go']['main']['App']['AddDiscoveredRepos'](arg1, arg2);
}

export function AddMirrorGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMirrorGroup'](arg1, arg2, arg3);
}

export function AddMirrorRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddMirrorRepo'](arg1, arg2, arg3, arg4);
}

export function AdoptOrphans(arg1) {
  return window['go']['main']['App']['AdoptOrphans'](arg1);
}

export function ApplyDiscoveredMirrors() {
  return window['go']['main']['App']['ApplyDiscoveredMirrors']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function ChangeCredentialType(arg1, arg2) {
  return window['go']['main']['App']['ChangeCredentialType'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckGlobalIdentity() {
  return window['go']['main']['App']['CheckGlobalIdentity']();
}

export function CheckMirrorCredentials(arg1) {
  return window['go']['main']['App']['CheckMirrorCredentials'](arg1);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function ConfirmSweep(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSweep'](arg1, arg2);
}

export function CreateNewRepo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateNewRepo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CredentialDelete(arg1) {
  return window['go']['main']['App']['CredentialDelete'](arg1);
}

export function CredentialRegenerateSSH(arg1) {
  return window['go']['main']['App']['CredentialRegenerateSSH'](arg1);
}

export function CredentialSetupGCM(arg1) {
  return window['go']['main']['App']['CredentialSetupGCM'](arg1);
}

export function CredentialSetupSSH(arg1) {
  return window['go']['main']['App']['CredentialSetupSSH'](arg1);
}

export function CredentialStoreToken(arg1, arg2) {
  return window['go']['main']['App']['CredentialStoreToken'](arg1, arg2);
}

export function CredentialVerify(arg1) {
  return window['go']['main']['App']['CredentialVerify'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteMirrorGroup(arg1) {
  return window['go']['main']['App']['DeleteMirrorGroup'](arg1);
}

export function DeleteMirrorRepo(arg1, arg2) {
  return window['go']['main']['App']['DeleteMirrorRepo'](arg1, arg2);
}

export function DeleteRepo(arg1, arg2) {
  return window['go']['main']['App']['DeleteRepo'](arg1, arg2);
}

export function DetectEditors() {
  return window['go']['main']['App']['DetectEditors']();
}

export function DetectTerminals() {
  return window['go']['main']['App']['DetectTerminals']();
}

export function Discover(arg1) {
  return window['go']['main']['App']['Discover'](arg1);
}

export function DiscoverMirrors() {
  return window['go']['main']['App']['DiscoverMirrors']();
}

export function FetchAllRepos() {
  return window['go']['main']['App']['FetchAllRepos']();
}

export function FetchRepo(arg1, arg2) {
  return window['go']['main']['App']['FetchRepo'](arg1, arg2);
}

export function FindOrphans() {
  return window['go']['main']['App']['FindOrphans']();
}

export function GetAllStatus() {
  return window['go']['main']['App']['GetAllStatus']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigLoadError() {
  return window['go']['main']['App']['GetConfigLoadError']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetGlobalFolder() {
  return window['go']['main']['App']['GetGlobalFolder']();
}

export function GetMirrorStatus(arg1) {
  return window['go']['main']['App']['GetMirrorStatus'](arg1);
}

export function GetPeriodicSync() {
  return window['go']['main']['App']['GetPeriodicSync']();
}

export function GetRepoDetail(arg1, arg2) {
  return window['go']['main']['App']['GetRepoDetail'](arg1, arg2);
}

export function GetTokenGuide(arg1) {
  return window['go']['main']['App']['GetTokenGuide'](arg1);
}

export function GetViewMode() {
  return window['go']['main']['App']['GetViewMode']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsPositionOnScreen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IsPositionOnScreen'](arg1, arg2, arg3, arg4);
}

export function IsTestMode() {
  return window['go']['main']['App']['IsTestMode']();
}

export function ListAccountOrgs(arg1) {
  return window['go']['main']['App']['ListAccountOrgs'](arg1);
}

export function ListRemoteRepos(arg1) {
  return window['go']['main']['App']['ListRemoteRepos'](arg1);
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function OpenInApp(arg1, arg2) {
  return window['go']['main']['App']['OpenInApp'](arg1, arg2);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenInTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenInTerminal'](arg1, arg2, arg3);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PreviewSweep(arg1, arg2) {
  return window['go']['main']['App']['PreviewSweep'](arg1, arg2);
}

export function PullRepo(arg1, arg2) {
  return window['go']['main']['App']['PullRepo'](arg1, arg2);
}

export function RefreshStatus() {
  return window['go']['main']['App']['RefreshStatus']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RemoveGlobalIdentity() {
  return window['go']['main']['App']['RemoveGlobalIdentity']();
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetGlobalFolder(arg1) {
  return window['go']['main']['App']['SetGlobalFolder'](arg1);
}

export function SetPeriodicSync(arg1) {
  return window['go']['main']['App']['SetPeriodicSync'](arg1);
}

export function SetViewMode(arg1) {
  return window['go']['main']['App']['SetViewMode'](arg1);
}

export function SetupMirrorRepo(arg1, arg2) {
  return window['go']['main']['App']['SetupMirrorRepo'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SyncEditors() {
  return window['go']['main']['App']['SyncEditors']();
}

export function SyncTerminals() {
  return window['go']['main']['App']['SyncTerminals']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
