// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {identity} from '../models';

export function AddAccount(arg1:main.AddAccountRequest):Promise<void>;

export function AddDiscoveredRepos(arg1:string,arg2:Array<string>):Promise<void>;

export function AddMirrorGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddMirrorRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ApplyDiscoveredMirrors():Promise<void>;

export function ChangeCredentialType(arg1:string,arg2:string):Promise<void>;

export function CheckGlobalIdentity():Promise<identity.GlobalIdentityStatus>;

export function CheckMirrorCredentials(arg1:string):Promise<main.MirrorCredentialCheck>;

export function CloneRepo(arg1:string,arg2:string):Promise<void>;

export function CreateNewRepo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function CredentialDelete(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialRegenerateSSH(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupGCM(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialSetupSSH(arg1:string):Promise<main.CredentialSetupResult>;

export function CredentialStoreToken(arg1:string,arg2:string):Promise<main.CredentialSetupResult>;

export function CredentialVerify(arg1:string):Promise<main.CredentialStatus>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteMirrorGroup(arg1:string):Promise<void>;

export function DeleteMirrorRepo(arg1:string,arg2:string):Promise<void>;

export function DeleteRepo(arg1:string,arg2:string):Promise<void>;

export function Discover(arg1:string):Promise<void>;

export function DiscoverMirrors():Promise<void>;

export function FetchAllRepos():Promise<void>;

export function FetchRepo(arg1:string,arg2:string):Promise<void>;

export function GetAllStatus():Promise<Array<main.StatusResult>>;

export function GetAppVersion():Promise<string>;

export function GetAutostart():Promise<boolean>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetConfigLoadError():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetGlobalFolder():Promise<string>;

export function GetMirrorStatus(arg1:string):Promise<void>;

export function GetPeriodicSync():Promise<string>;

export function GetRepoDetail(arg1:string,arg2:string):Promise<main.RepoDetail>;

export function GetTokenGuide(arg1:string):Promise<main.TokenGuideInfo>;

export function GetViewMode():Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function IsTestMode():Promise<boolean>;

export function ListAccountOrgs(arg1:string):Promise<Array<string>>;

export function ListRemoteRepos(arg1:string):Promise<Array<main.DiscoverResult>>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function PullRepo(arg1:string,arg2:string):Promise<void>;

export function RefreshStatus():Promise<void>;

export function ReloadConfig():Promise<main.ConfigDTO>;

export function RemoveGlobalIdentity():Promise<void>;

export function RenameAccount(arg1:string,arg2:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetGlobalFolder(arg1:string):Promise<void>;

export function SetPeriodicSync(arg1:string):Promise<void>;

export function SetViewMode(arg1:string):Promise<void>;

export function SetupMirrorRepo(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateAccount(arg1:main.UpdateAccountRequest):Promise<void>;
